#!/usr/bin/python
#-*- coding: utf-8 -*-

import re
from flask import Flask
from flask import render_template
from flask import request
import requests
from bs4 import BeautifulSoup


app = Flask(__name__)

@app.route('/')
def index():
	return render_template('vaccine.html')
	
@app.route('/info', methods= ['POST'])
def info():
	error = None
	if request.method == 'POST':
		myurl = request.form['url']
		str = myurl
		url = str
		res = requests.get(url)
		html = BeautifulSoup(res.content,"html.parser")
		
		return render_template('info.html',url=myurl,parsed_page=html)
				
 
	
if __name__ == '__main__':
	
	
	app.run()
  
  info.html
  
  <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<body>
	<h1> URL </h1>
	<h3> URL : {{url}} </h3>
	{{parsed_page}}
</body>
</html>

  
